
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dnkmwnauihqnnmbcwibz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRua213bmF1aWhxbm5tYmN3aWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDA5NjEsImV4cCI6MjA2MTQxNjk2MX0.8SNkILcCxO-FdggW4g_oeMvyWZ8iauPOdmjMJYkg1DU";

// Define custom database types
export type Database = {
  public: {
    Tables: {
      bills: {
        Row: {
          id: string;
          bill_number: string;
          customer_email: string;
          total: number;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          bill_number: string;
          customer_email: string;
          total: number;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bill_number?: string;
          customer_email?: string;
          total?: number;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      bill_items: {
        Row: {
          id: string;
          bill_id: string;
          product_id: string | null;
          product_name: string;
          quantity: number;
          price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          bill_id: string;
          product_id?: string | null;
          product_name: string;
          quantity: number;
          price: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          bill_id?: string;
          product_id?: string | null;
          product_name?: string;
          quantity?: number;
          price?: number;
          created_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          product_id: string;
          name: string;
          price: number;
          stock: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          name: string;
          price: number;
          stock?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          name?: string;
          price?: number;
          stock?: number;
          created_at?: string;
        };
      };
      company_profiles: {
        Row: {
          id: string;
          user_id: string;
          company_name: string;
          address: string;
          phone: string;
          email: string;
          gstin: string;
          state: string;
          bank_name: string;
          account_number: string;
          ifsc_code: string;
          account_holder_name: string;
          logo_url: string | null;
          signature_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_name: string;
          address: string;
          phone: string;
          email: string;
          gstin: string;
          state: string;
          bank_name: string;
          account_number: string;
          ifsc_code: string;
          account_holder_name: string;
          logo_url?: string | null;
          signature_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_name?: string;
          address?: string;
          phone?: string;
          email?: string;
          gstin?: string;
          state?: string;
          bank_name?: string;
          account_number?: string;
          ifsc_code?: string;
          account_holder_name?: string;
          logo_url?: string | null;
          signature_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  storage: {
    Tables: {
      objects: {
        Row: {
          id: string;
          bucket_id: string;
          name: string;
        };
        Insert: {
          id?: string;
          bucket_id: string;
          name: string;
        };
        Update: {
          id?: string;
          bucket_id?: string;
          name?: string;
        };
      };
      buckets: {
        Row: {
          id: string;
          name: string;
        };
        Insert: {
          id: string;
          name: string;
        };
        Update: {
          id?: string;
          name?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
